#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftSpeed = 100;
int rightSpeed = 100;
float Rrpm = 0;
float Lrpm = 0;

task main(){
  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;

  while(true){
    SensorValue[leftEncoder] = 0;
    SensorValue[rightEncoder] = 0;
    delay(50);
    Rrpm = abs(SensorValue[rightEncoder])/0.050;
    Lrpm = abs(SensorValue[leftEncoder])/0.050;
    if(Lrpm > Rrpm)
    {
    	rightSpeed++;
    	motor[rightMotor] = rightSpeed;
    	leftSpeed--;
    	motor[leftMotor] = leftSpeed;
    }
    if(Lrpm < Rrpm)
    {
    	leftSpeed++;
    	motor[leftMotor] = leftSpeed;
    	rightSpeed--;
    	motor[rightMotor] = rightSpeed;
    }
    if(Lrpm == Rrpm)
    {
      leftSpeed = 110;
    	rightSpeed = 110;
    	motor[rightMotor] = rightSpeed;
    	motor[leftMotor] = leftSpeed;
    }
    if(rightSpeed > 127){
      rightSpeed = 127;
    }
    if(leftSpeed > 127){
      leftSpeed = 127;
    }
    if(rightSpeed < 0){
      rightSpeed = 0;
    }
    if(leftSpeed < 0){
      leftSpeed = 0;
    }
  }
}
